/* Change background colour. */

/* No symmetry */
set symmetry off;

/* antialias default on */
view -wuantialias false;
view -antialias true;

/* shadows on */
/*view -realspheres true;
view -shadows true;*/

molecule load mol  'examples/ca_rec.pdb';
molecule load cc0  'examples/ca_cc.000.017.pdb';
molecule load cc1  'examples/ca_cc.001.015.pdb';
molecule load cc2  'examples/ca_cc.002.014.pdb';
molecule load cc3  'examples/ca_cc.003.014.pdb';
molecule load cc4  'examples/ca_cc.004.014.pdb';
molecule load cc5  'examples/ca_cc.005.010.pdb';
molecule load cc6  'examples/ca_cc.006.007.pdb';
molecule load cc7  'examples/ca_cc.007.002.pdb';
molecule load lig1 'examples/dorzolamide_ca.pdb';

/* display as cartoon */
display lines off molecule mol;
/* assign secondary structure and display the protein as cartoon */
secstruc molecule mol;
schematic -name protein_schematic molecule mol;
display spheres on name ZN;
label %a name ZN;

display lines off molecule lig1;
display sticks on molecule lig1;
color White molecule lig1 and atom C*;


color Cyan molecule cc0 and atom C*;
color Purple molecule cc1 and atom C*;
color Yellow molecule cc2 and atom C*;
color Salmon molecule cc3 and atom C*;
color Plum molecule cc4 and atom C*;
color Blue molecule cc5 and atom C*;
color Orange molecule cc6 and atom C*;
color Green molecule cc7 and atom C*;
display lines off molecule cc3;
display lines off molecule cc4;
display lines off molecule cc5;
display lines off molecule cc7;

center molecule lig1 or molecule cc0 or molecule cc1 or molecule cc2 or molecule cc6;
