ATOM      1  N1  ACD     1       0.713  -0.083   0.000   1.000          AAAA
ATOM      2  C2  ACD     1      -0.626  -0.047   0.000   1.000          AAAA
ATOM      3  C3  ACD     1      -1.194   1.355   0.000   1.000          AAAA
ATOM      4  O4  ACD     1      -1.346  -1.039   0.000   1.000          AAAA
ATOM      5  H1  ACD     1       1.204  -0.951   0.000   1.000          AAAA
ATOM      6  H2  ACD     1       1.248   0.764   0.000   1.000          AAAA
END