REMARK  NONE *                                                                        
REMARK   DATE:     9/12/ 7     11:52:11      CREATED BY USER: gychuang                
ATOM      1  N1  ACD     1       0.705  -0.072   0.000  1.00  0.00      AAAA
ATOM      2  C2  ACD     1      -0.636  -0.048   0.000  1.00  0.00      AAAA
ATOM      3  C3  ACD     1      -1.211   1.353   0.000  1.00  0.00      AAAA
ATOM      4  O4  ACD     1      -1.347  -1.041   0.000  1.00  0.00      AAAA
ATOM      5  H1  ACD     1       1.203  -0.940   0.000  1.00  0.00      AAAA
ATOM      6  H2  ACD     1       1.233   0.777   0.000  1.00  0.00      AAAA
END
