REMARK  NONE *                                                                        
REMARK   DATE:     9/12/ 7     14:12:43      CREATED BY USER: gychuang                
ATOM      1  C1  ACN     1       0.563  -0.199  -1.225  1.00  0.00      AAAA
ATOM      2  C2  ACN     1      -0.039   0.014   0.088  1.00  0.00      AAAA
ATOM      3  N   ACN     1      -0.522   0.184   1.130  1.00  0.00      AAAA
END
